# Generated by Django 2.0.4 on 2018-04-26 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ci',
            fields=[
                ('value', models.IntegerField(primary_key=True, serialize=False)),
                ('rhythmic', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ci',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ciauthor',
            fields=[
                ('value', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('long_desc', models.TextField(blank=True, null=True)),
                ('short_desc', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ciauthor',
                'managed': False,
            },
        ),
    ]
